version: '3.8'

services:
  web:
    build: ./
    command: gunicorn -b :80 --access-logfile ./logs/access.log  --error-logfile ./logs/errors.log --log-file ./logs/logs.log --log-level INFO server:app --workers=8 --worker-class gthread --threads 8
    # command: python manage.py run -h 0.0.0.0
    volumes:
      - ./:/usr/src/app/
      - upload_files:/usr/src/app/app/uploads/
    ports:
      - 80:80
    env_file:
      - ./.env.docker
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - LANG=pt_BR.UTF-8
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=teste
      - POSTGRES_DB=desafio
    ports:
      - 6543:5432
networks:
  my_docker_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
volumes:
  postgres_data:
  upload_files: