from sqlalchemy import BigInteger, String, Numeric, Date, Column, Integer
from sqlalchemy.orm import declarative_base
from app.core.db import db
Base = declarative_base()

class CessaoFundo(Base, db.Model):
    __tablename__ = 'cessao_fundo'
    ID_CESSAO = Column(Integer, nullable=False, primary_key=True)
    ORIGINADOR = Column(String(250), nullable=False)
    DOC_ORIGINADOR = Column(BigInteger, nullable=False)
    CEDENTE = Column(String(250), nullable=False)
    DOC_CEDENTE = Column(BigInteger, nullable=False)
    CCB = Column(Integer, nullable=False)
    ID_EXTERNO = Column(Integer, nullable=False)
    CLIENTE = Column(String(250), nullable=False)
    CPF_CNPJ = Column(String(50), nullable=False)
    ENDERECO = Column(String(250), nullable=False)
    CEP = Column(String(50), nullable=False)
    CIDADE = Column(String(250), nullable=False)
    UF = Column(String(50), nullable=False)
    VALOR_DO_EMPRESTIMO = Column(Numeric(10,2), nullable=False)
    VALOR_PARCELA = Column(Numeric(10,2), nullable=False)
    TOTAL_PARCELAS = Column(Integer, nullable=False)
    PARCELA = Column(Integer, nullable=False)
    DATA_DE_EMISSAO = Column(Date, nullable=False)
    DATA_DE_VENCIMENTO = Column(Date, nullable=False)
    DATA_DE_COMPRA_CCB = Column(Date, nullable=False)
    PRECO_DE_AQUISICAO = Column(Numeric(10,2), nullable=False)
    TAXA_DE_JUROS = Column(Numeric(10,2), nullable=False)
    PRINCIPAL = Column(Numeric(10,2), nullable=False)
    JUROS = Column(Numeric(10,2), nullable=False)
    IOF = Column(Numeric(10,2), nullable=False)
    COMISSAO = Column(Numeric(10,2), nullable=False)
    MULTA = Column(Numeric(10,2), nullable=False)
    MORA = Column(Numeric(10,2), nullable=False)
